export const FETCH_BOOK_CATEGORIES_REQUEST = "FETCH_BOOK_CATEGORIES_REQUEST";
export const FETCH_BOOK_CATEGORIES_LOADING = "FETCH_BOOK_CATEGORIES_LOADING";
export const FETCH_BOOK_CATEGORIES_SUCCESS = "FETCH_BOOK_CATEGORIES_SUCCESS";
export const FETCH_BOOK_CATEGORIES_FAILED = "FETCH_BOOK_CATEGORIES_FAILED";
export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const FETCH_BOOK_CATEGORIES_DETAIL_REQUEST = "FETCH_BOOK_CATEGORIES_DETAIL_REQUEST";
export const FETCH_BOOK_CATEGORIES_DETAIL_SUCCESS = "FETCH_BOOK_CATEGORIES_DETAIL_SUCCESS";
export const FETCH_BOOK_CATEGORIES_DETAIL_FAILED = "FETCH_BOOK_CATEGORIES_DETAIL_FAILED";


export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';

export const CREATE_BOOK_LOADING = 'CREATE_BOOK_LOADING';
export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';

export const UPDATE_BOOK_LOADING = 'UPDATE_BOOK_LOADING';
export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
